### PR TITLE
scoped-properties/ -> settings/ (deprecation fix)

### LINKED ISSUE #5: Package.loadSettings is deprecated.
Store package settings files in the `settings/` directory instead of `scoped-properties/`

```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:547:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:168:43)
```

### PR DESCRIPTION
**Pull request by dead-claudia**
Fixes #5.

### CODE REVIEW

**Comment by Mouq** [comment]
Uh, looks like you forgot to add the file after it was moved to `settings/`

**Comment by dead-claudia** [comment]
Oops... Forgot `git commit -a` does nothing with "new" files.

**Comment by dead-claudia** [comment]
That should fix it.

I keep on forgetting that `git commit -a ...` only adds changed files, not new or renamed ones like `git add --all` does.

**Comment by dead-claudia** [comment]
@yhsiang Ping

**Comment by dead-claudia** [comment]
FWIW, this won't work with Atom 1.0 when it comes out this month.

**Comment by ghost** [comment]
Atom 1.0 is just released!
... and language-livescript package is deprecated!

**Comment by dead-claudia** [comment]
@yhsiang Ping...

**Comment by LinusU** [comment]
@yhsiang ping!

**Comment by bumxu** [comment]
Fixed with 38bf537aa107bca26ab14fbece77cb2e5fb52a47.
Thank you! 👍

**Pull request closed without merging**
